# Generated by Django 4.2.7 on 2023-12-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todos",
            name="deadline",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="todos",
            name="finished_at",
            field=models.DateField(null=True),
        ),
    ]
